name = "echonetlite"
main = "src/_worker.ts"
compatibility_date = "2024-01-01"

# Assets configuration
[assets]
directory = "dist"

# Custom domain routing
[[routes]]
pattern = "echonet-lite.ka2n.dev"
custom_domain = true
